---
- hosts: mywebservers
  become: yes
  gather_facts: yes
  tasks:

  - name: i want to install apache2 webserver on ansible nodes
    apt:
     name: "{{mywebserverpackonubuntu}}"
     state: present
    when: ansible_os_family== "Debian"

  - name: i want to start webserver
    service:
      name: "{{mywebserverpackonubuntu}}"
      state: started
    when: ansible_os_family== "Debian"

  
  - name: i want to install Redhat on ansible nodes
    apt:
     name: "{{mywebserverpackonredhat}}"
     state: present
    when: ansible_os_family== "RedHat"

  - name: i want to start webserver
    service:
      name: "{{mywebserverpackonredhat}}"
      state: started
    when: ansible_os_family== "RedHat"  