---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  
  - name: i want to install Redhat on ansible nodes
    apt:
     name: httpd
     state: present
    when: ansible_os_family== "RedHat"

  - name: i want to start webserver
    service:
      name: httpd
      state: started
    when: ansible_os_family== "RedHat"  